language: cpp
compiler: gcc
sudo: true
dist: trusty

env:
  global:
    - CC_TEST_REPORTER_ID=2727af6b46213a350cb85449e8d3b538edcd7221168f668c940ef86f07718184
    - GIT_COMMITTED_AT=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then git log -1 --pretty=format:%ct; else git log -1 --skip 1 --pretty=format:%ct; fi)

before_install:
  - wget http://download.opensuse.org/repositories/home:hpcoder1/xUbuntu_14.04/Release.key
  - sudo apt-key add - < Release.key
  - echo 'deb http://download.opensuse.org/repositories/home:/hpcoder1/xUbuntu_14.04/ /' >/tmp/hpcoders.list 
  - sudo mv /tmp/hpcoders.list /etc/apt/sources.list.d/
  - sudo apt-get update -qq
  - sudo apt-get install -y json-spirit
  - sudo apt-get install -y libboost-dev
  - sudo apt-get install -y libxml2-utils
  - sudo apt-get install -y python3-pip
  - sudo pip3 install meson
  - git clone https://github.com/colincross/ninja
  - cd ninja
  - ./configure.py --bootstrap
  - sudo install ninja /usr/bin
script: 
  -  meson -C build
  -  cd build
  -  ninja
